"$schema" = 'https://starship.rs/config-schema.json'

format = """
$os\
$status\
$directory\
$git_branch\
$git_status\
$fill\
$golang\
$nodejs\
$bun\
$deno\
$python\
$java\
$zig\
$rust\
$c\
$cmd_duration\
$time\
$line_break\
$character\
"""

# palette = "rose-pine"
add_newline = true

# [palettes.rose-pine]
# foreground = '#D9E0EE'
# background = '#1E1E2E'
# current_line = '#2E2E3E'
# primary = '#313244'
# box = '#2E2E3E'
# blue = '#31748f'
# cyan = '#9ccfd8'
# green = '#A6E3A1'
# orange = '#ebbcba'
# pink = '#F5BDE6'
# purple = '#c4a7e7'
# red = '#F38BA8'
# yellow = '#f6c177'
# status = '#eb6f92'


[os]
format = '(fg:bright-black)[î‚¶](fg:white)[$symbol ](fg:black bg:white)[î‚´](fg:white)'
disabled = false

[status]
format = " (fg:bright-black)[î‚¶](fg:red)[î½¶](fg:black bg:red)[î‚´](fg:red bg:bright-black)[ $status](fg:white bg:bright-black)[î‚´](fg:bright-black)"
pipestatus = true
pipestatus_separator = "-"
pipestatus_segment_format = "$status"
pipestatus_format = " (fg:bright-black)[î‚¶](fg:red)[î½¶](fg:black bg:red)[î‚´](fg:red bg:bright-black)[ $pipestatus](fg:white bg:bright-black)[î‚´](fg:bright-black)"
disabled = false

[directory]
format = ' (fg:bright-black)[î‚¶](fg:cyan)[ó°· ](fg:black bg:cyan)[î‚´](fg:cyan bg:bright-black)[ $read_only$truncation_symbol$path](fg:white bg:bright-black)[î‚´](fg:bright-black)'
home_symbol = "î­† ~"
truncation_symbol = 'î¯Ÿ '
truncation_length = 5
read_only = 'ó±§µ '
read_only_style = ''

[git_branch]
format = ' (fg:bright-black)[î‚¶](fg:green)[$symbol ](fg:black bg:green)[î‚´](fg:green bg:bright-black)[ $branch](fg:white bg:bright-black)'
symbol = 'ï—'

[git_status]
format = '[$all_status](fg:green bg:bright-black)[î‚´](fg:bright-black)'
conflicted = ' ='
up_to_date = ''
untracked = ' ?${count}'
stashed = ' $'
modified = ' !${count}'
staged = ' +'
renamed = ' Â»'
deleted = ' âœ˜'
ahead = ' â‡¡${count}'
diverged = ' â‡•â‡¡${ahead_count}â‡£${behind_count}'
behind = ' â‡£${count}'

[nodejs]
format = ' (fg:bright-black)[î‚¶](fg:green)[$symbol ](fg:black bg:green)[î‚´](fg:green bg:bright-black)[ $version](fg:white bg:bright-black)[î‚´](fg:bright-black)'
symbol = 'ó°™ Node.js'

[bun]
format = ' (fg:bright-black)[î‚¶](fg:green)[$symbol ](fg:black bg:green)[î‚´](fg:green bg:bright-black)[ $version](fg:white bg:bright-black)[î‚´](fg:bright-black)'
symbol = 'î¯ Bun'

[deno]
format = ' (fg:bright-black)[î‚¶](fg:purple)[$symbol ](fg:black bg:purple)[î‚´](fg:purple bg:bright-black)[ $version](fg:white bg:bright-black)[î‚´](fg:bright-black)'
symbol = 'ğŸ¦• Deno'

[zig]
format = ' (fg:bright-black)[î‚¶](fg:blue)[$symbol ](fg:black bg:blue)[î‚´](fg:blue bg:bright-black)[ $version](fg:white bg:bright-black)[î‚´](fg:bright-black)'
symbol = 'âš¡ï¸ Zig'

[rust]
format = ' (fg:bright-black)[î‚¶](fg:yellow)[$symbol ](fg:black bg:yellow)[î‚´](fg:yellow bg:bright-black)[ $version](fg:white bg:bright-black)[î‚´](fg:bright-black)'
symbol = 'î¨ Rust'

[python]
format = ' (fg:bright-black)[î‚¶](fg:green)[$symbol ](fg:black bg:green)[î‚´](fg:green bg:bright-black)[ (${version} )(\($virtualenv\) )](fg:white bg:bright-black)[î‚´](fg:bright-black)'
symbol = 'îœ¼ python'

[java]
format = ' (fg:bright-black)[î‚¶](fg:red)[$symbol ](fg:black bg:red)[î‚´](fg:red bg:bright-black)[ $version](fg:white bg:bright-black)[î‚´](fg:bright-black)'
symbol = 'îœ¸ Java'

[golang]
format = ' (fg:bright-black)[î‚¶](fg:red)[$symbol ](fg:black bg:red)[î‚´](fg:red bg:bright-black)[ $version](fg:white bg:bright-black)[î‚´](fg:bright-black)'
symbol = 'ó°‘® Go'

[c]
format = ' (fg:bright-black)[î‚¶](fg:blue)[$symbol ](fg:black bg:blue)[î‚´](fg:blue bg:bright-black)[ $version](fg:white bg:bright-black)[î‚´](fg:bright-black)'
symbol = 'î˜ C'

[fill]
symbol = ' '
style = 'fg:bright-black'

[cmd_duration]
min_time = 500
format = ' (fg:bright-black)[î‚¶](fg:yellow)[ïƒ§ ](fg:black bg:yellow)[î‚´](fg:yellow bg:bright-black)[ $duration](fg:white bg:bright-black)[î‚´](fg:bright-black)'

[time]
format = ' (fg:bright-black)[î‚¶](fg:white)[ó°¦– ](fg:black bg:white)[î‚´](fg:white bg:bright-black)[ $time](fg:white bg:bright-black)[î‚´](fg:bright-black)'
time_format = '%H:%M'
disabled = false

[username]
format = ' (fg:bright-black)[î‚¶](fg:yellow)[ï• ](fg:black bg:yellow)[î‚´](fg:yellow bg:bright-black)[ $user](fg:white bg:bright-black)[î‚´](fg:bright-black) '
show_always = true

[character]
format = '[$symbol ](fg:bright-black) '
success_symbol = '[ïƒš](fg:bold white)'
error_symbol = '[ïƒš](fg:bold red)'

[profiles]
transient = """$character"""

[os.symbols]
Alpaquita = "îª¢ "
Alpine = "ïŒ€ "
AlmaLinux = "ïŒ "
Amazon = "ï‰° "
Android = "ï…» "
Arch = "ïŒƒ "
Artix = "ïŒŸ "
CachyOS = "ïŒƒ "
CentOS = "ïŒ„ "
Debian = "ïŒ† "
DragonFly = "îŠ "
Emscripten = "ïˆ… "
EndeavourOS = "ï†— "
Fedora = "ïŒŠ "
FreeBSD = "ïŒŒ "
Garuda = "ó°›“ "
Gentoo = "ïŒ "
HardenedBSD = "ó°Œ "
Illumos = "ó°ˆ¸ "
Kali = "ïŒ§ "
Linux = "ïŒš "
Mabox = "î¬© "
Macos = "îœ‘"
Manjaro = "ïŒ’ "
Mariner = "ï‡ "
MidnightBSD = "ï†† "
Mint = "ïŒ "
NetBSD = "ï€¤ "
NixOS = "ïŒ“ "
Nobara = "ï€ "
OpenBSD = "ó°ˆº "
openSUSE = "ïŒ” "
OracleLinux = "ó°Œ· "
Pop = "ïŒª "
Raspbian = "ïŒ• "
Redhat = "ïŒ– "
RedHatEnterprise = "ïŒ– "
RockyLinux = "ïŒ« "
Redox = "ó°€˜ "
Solus = "ó° ³ "
SUSE = "ïŒ” "
Ubuntu = "ïŒ› "
Unknown = "ïˆ­ "
Void = "ïŒ® "
Windows = "ó°² "
